### PR TITLE
Set maximum width to 40rem across screen sizes

### PR DESCRIPTION
**Pull request by McSinyx**
Referencing GH-45: 50% is really narrow on smaller screen sizes, the maximum width should instead be calculated from the font size.

Some rules are removed to correct the bounding box size
in browser inspector and fix the overflow on the x-axis.

The now-unused div.parent is removed; please hide whitespace changes when view the diff for better clarity.

### CODE REVIEW

**Comment by httpjamesm** [comment]
Hmm... On smaller windows I'm seeing overflowing on the X axis on the homepage.

image

On mobile devices, the answer pages lack padding.

image

And on large devices (this is an extreme example), this version is actually narrower than the current version.

Screenshot 2024-04-22 at 19 19 44

vs

Screenshot 2024-04-22 at 19 19 58

**Comment by McSinyx** [comment]
> On smaller windows I'm seeing overflowing on the X axis on the homepage.

Oops, sorry, I forgot to check the home page.  The style sheets are unified now.

> On mobile devices, the answer pages lack padding.

Silly me, I switched to CSS variable last minute and didn't realize var doesn't work for media queries.  Padding should be restored now.

> And on large devices (9000x5918), this version is actually narrower than the current version.

This is expected.  Re GH-45: readability is improved by shortening the [line length is characters](https://en.wikipedia.org/wiki/Line_length).  I switched to 40rem for backward compatibility with the old home page's width, also to roughly accommodate the standard 80-column terminal output.

People with high-res display would usually enable HiDPI or adjust the font size so it should not be an issue in practice.

**Comment by httpjamesm** [comment]
There are still issues. The homepage is no longer vertically centered, probably due to the removal of the parent div.

image

**Comment by McSinyx** [comment]
You are right, and I am horribly sorry I didn't check that.

**Comment by McSinyx** [comment]
The original stylesheet's issue where it's impossible
to scroll to the top of a vertically overflowed home page
is also fixed now.

**Pull request merged**
